---
- name: reset cluster
  become: yes
  shell: kubeadm reset --force
  tags:
    - reset_cluster

- name: initialize cluster
  become: yes
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address="{{ ansible_eth0.ipv4.address }}" --kubernetes-version={{ kubernetes_version }}
  register: join_command_string
  tags:
    - initialize_cluster

- name: create $HOME/.kube directory
  file:
    path: /home/teligent/.kube
    state: directory
    mode: 0755
  tags:
    - kube_directory

- name: copy kubernetes config
  become: yes
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: /home/teligent/.kube/config
    owner: teligent
  tags:
    - kubernetes_config      

#- name: add weave addon
#  become: yes
#  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
#  tags:
#    - weave config

- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_string
  tags:
    - join_nodes

- debug:
    var: join_command_string
  tags:
    - join_nodes

- name: set join command
  set_fact:
    join_command: "{{ join_command_string.stdout_lines[0] }}"
  tags:
    - join_nodes

- debug:
    var: join_command
  tags:
    - join_nodes
